# Generated by Django 2.1.4 on 2018-12-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='code_info',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('userName', models.CharField(max_length=50, verbose_name='Git用户名')),
                ('verNO', models.CharField(db_index=True, max_length=20, verbose_name='版本号')),
                ('fileList', models.TextField(max_length=500, verbose_name='发布文件列表')),
                ('TSDate', models.DateTimeField(verbose_name='测试环境发布时间')),
                ('OSDate', models.DateTimeField(verbose_name='正式环境发布时间')),
                ('TSStatus', models.IntegerField(verbose_name='测试环境发布状态')),
                ('OSStatus', models.IntegerField(verbose_name='正式环境发布状态')),
                ('RBStatus', models.IntegerField(verbose_name='回滚状态')),
            ],
        ),
        migrations.CreateModel(
            name='code_user',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('userName', models.CharField(max_length=50, verbose_name='Git用户名')),
                ('userEmail', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('userPassword', models.CharField(max_length=50, verbose_name='用户Git密码')),
            ],
        ),
    ]
