# Generated by Django 2.1.4 on 2018-12-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_mage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPassword',
            field=models.CharField(max_length=100, verbose_name='用户Git密码'),
        ),
    ]
